version: "3.9"
services:
  ollama:
    image: ollama/ollama
    ports: ['11434:11434']
    volumes: ['./.ollama:/root/.ollama']
  api:
    build: .
    command: uvicorn apps.api.main:app --host 0.0.0.0 --port 8000
    env_file: .env
    volumes: ['.:/app']
    depends_on: [ollama]
    ports: ['8000:8000']
